version: '3'
services:
   postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-mybd}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-mysecretpassword}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
